services:
  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/log:/var/log/nginx
  php:
    build:
      context: ./docker
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  print-status:
    image: busybox
    command: "echo '---\nSERVER RUNNING AT http://localhost:8000. USE CTRL+C TO TERMINATE.\n---'"
    depends_on:
      php:
        condition: service_started
      web:
        condition: service_started
